name: "Build phuc corne"
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano"]'
      shield: '["corne_left","corne_right"]'
      alphas: '["QWERTY"]'
      nav: '["invertedT"]'
      clipboard: '["win"]'
      kconfig: '["CONFIG_ZMK_DISPLAY=y\nCONFIG_ZMK_POINTING=y"]'
  settings_reset:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano"]'
      shield: '["settings_reset"]'
